[project]
name = "cluster_sf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy", "astropy", "regions", "numba", "scipy", "tqdm", "numb a"]
